project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - GreenCollectivesReadMe.md
    - projectPage.md
sidebar:
  contents:
    - about.qmd

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Additional Projects"  
        file: projectPage.md
  
    
format:
  html:
    theme:
      dark: darkly
      light: flatly
      
    css: styles.css
    toc: true
    font-family: sans-serif