project:
  type: website
  output-dir: docs
sidebar:
  contents:
    - about.qmd
website:
  title: "Tyler"
  navbar: 
    search: true
    background: primary
  
    
format:
  html:
    theme:
      dark: darkly
      light: flatly
      
    css: styles.css
    toc: true
    font-family: sans-serif